### ISSUE TITLE
Sorting and Searching

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/CppPrograms#9]
### Add searching and sorting programs and please make folder with your name and then add into it.

Anyone who already pushed his/her work can also do the same if possible

**Comment by Sanchitbajaj02** [comment]
And I am ready to merge that in master

**Comment by bhavesh1129** [comment]
Can I also contribute to this?

**Comment by dyutimangal** [comment]
I want to contribute. I can write MergeSort algorithm in recursive version.

**Comment by Sanchitbajaj02** [comment]
@bhavesh1129 and @dyutimangal you can contribute in this

**Comment by shubhangi-singh21** [comment]
@Sanchitbajaj02 I would like to add selection sort if you permit!

**Comment by Sanchitbajaj02** [comment]
@shubhangi-singh21 yes, you can

**Comment by SravanthiKaki** [comment]
Can I work on bucket sort in Java?

**Comment by Sanchitbajaj02** [comment]
@SravanthiKaki yes, you can
